version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  api:
    build: .
    restart: unless-stopped
    ports:
      - "3335:3335"
    environment:
      - DATABASE_URL=mongodb://admin:secret@mongo:27017/ecommerce?authSource=admin&directConnection=true&serverSelectionTimeoutMS=2000
      - JWT_SECRET=chave-super-secreta
      - CLOUDINARY_CLOUD_NAME=seu_cloud_name
      - CLOUDINARY_API_KEY=seu_api_key
      - CLOUDINARY_API_SECRET=seu_api_secret
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      - mongo
    command: ["bun", "--watch", "run", "src/index.ts"]

volumes:
  mongo_data:
